### PR TITLE
Not having a .bash_profile file shouldn't silently break this plugin

### PR DESCRIPTION
**Pull request by lpetre**
Great Plugin. I just installed it and it was silently failing. The cause was that I don't have a .bash_profile on this machine (osx).

### CODE REVIEW

**Comment by ericmartel** [comment]
This is great, thank you! I'm not a Mac user, how does the "global paths" work on OSX if you don't have a bash profile file?  How does ST2 locate your p4 install without it?  (I know, I really should get a Mac :/)

**Comment by evanbernstein** [comment]
I just spent the last 2 hours frantically wondering why perforce suddenly stopped working for me in sublime and finally tracked it down to this change.  This does not work for me on my mac.  The ~ is not being resolved.  I think this change should be reverted.

**Comment by ericmartel** [comment]
That's unfortunate, it seemed pretty safe!  I will revert it for now and try to get my hands on a mac to properly debug it

**Comment by evanbernstein** [comment]
Yeah, I agree.  It does look pretty safe and I don't know why it doesn't work.  Very odd.

**Comment by ericmartel** [comment]
Reverted the change

**Pull request merged**
